#pragma once
#ifndef TAHD_MACRO_FUNCTIONS_H
#define TAHD_MACRO_FUNCTIONS_H

#define MACRO_ARGS_COUNT(x1,   x2,   x3,   x4,   x5,   x6,   x7,   x8,   x9,   x10,  x11,  x12,  x13,  x14,  x15,  x16,  \
                         x17,  x18,  x19,  x20,  x21,  x22,  x23,  x24,  x25,  x26,  x27,  x28,  x29,  x30,  x31,  x32,  \
                         x33,  x34,  x35,  x36,  x37,  x38,  x39,  x40,  x41,  x42,  x43,  x44,  x45,  x46,  x47,  x48,  \
                         x49,  x50,  x51,  x52,  x53,  x54,  x55,  x56,  x57,  x58,  x59,  x60,  x61,  x62,  x63,  x64,  \
                         x65,  x66,  x67,  x68,  x69,  x70,  x71,  x72,  x73,  x74,  x75,  x76,  x77,  x78,  x79,  x80,  \
                         x81,  x82,  x83,  x84 , x85,  x86,  x87,  x88,  x89,  x90,  x91,  x92,  x93,  x94,  x95,  x96,  \
                         x97,  x98,  x99,  x100, x101, x102, x103, x104, x105, x106, x107, x108, x109, x110, x111, x112, \
                         x113, x114, x115, x116, x117, x118, x119, x120, x121, x122, x123, x124, x125, x126, x127, x128, \
                         x129, x130, x131, x132, x133, x134, x135, x136, x137, x138, x139, x140, x141, x142, x143, x144, \
                         x145, x146, x147, x148, x149, x150, x151, x152, x153, x154, x155, x156, x157, x158, x159, x160, \
                         x161, x162, x163, x164, x165, x166, x167, x168, x169, x170, x171, x172, x173, x174, x175, x176, \
                         x177, x178, x179, x180, x181, x182, x183, x184, x185, x186, x187, x188, x189, x190, x191, x192, \
                         x193, x194, x195, x196, x197, x198, x199, x200, x201, x202, x203, x204, x205, x206, x207, x208, \
                         x209, x210, x211, x212, x213, x214, x215, x216, x217, x218, x219, x220, x221, x222, x223, x224, \
                         x225, x226, x227, x228, x229, x230, x231, x232, x233, x234, x235, x236, x237, x238, x239, x240, \
                         x241, x242, x243, x244, x245, x246, x247, x248, x249, x250, x251, x252, x253, x254, x255, x256, \
                         res, ...) res
#define MACRO_ARGS_SIZE(...) MACRO_ARGS_COUNT(__VA_ARGS__,                                                               \
                                         256, 255, 254, 253, 252, 251, 250, 249, 248, 247, 246, 245, 244, 243, 242, 241, \
                                         240, 239, 238, 237, 236, 235, 234, 233, 232, 231, 230, 229, 228, 227, 226, 225, \
                                         224, 223, 222, 221, 220, 219, 218, 217, 216, 215, 214, 213, 212, 211, 210, 209, \
                                         208, 207, 206, 205, 204, 203, 202, 201, 200, 199, 198, 197, 196, 195, 194, 193, \
                                         192, 191, 190, 189, 188, 187, 186, 185, 184, 183, 182, 181, 180, 179, 178, 177, \
                                         176, 175, 174, 173, 172, 171, 170, 169, 168, 167, 166, 165, 164, 163, 162, 161, \
                                         160, 159, 158, 157, 156, 155, 154, 153, 152, 151, 150, 149, 148, 147, 146, 145, \
                                         144, 143, 142, 141, 140, 139, 138, 137, 136, 135, 134, 133, 132, 131, 130, 129, \
                                         128, 127, 126, 125, 124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, \
                                         112, 111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100, 99,  98,  97,  \
                                         96,  95,  94,  93,  92,  91,  90,  89,  88,  87,  86,  85,  84,  83,  82,  81,  \
                                         80,  79,  78,  77,  76,  75,  74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  \
                                         64,  63,  62,  61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,  \
                                         48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,  35,  34,  33,  \
                                         32,  31,  30,  29,  28,  27,  26,  25,  24,  23,  22,  21,  20,  19,  18,  17,  \
                                         16,  15,  14,  13,  12,  11,  10,  9,   8,   7,   6,   5,   4,   3,   2,   1)

#define MACRO_FOREACH_1(f, context, sep, arg) f(context, arg)
#define MACRO_FOREACH_2(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_1(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_3(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_2(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_4(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_3(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_5(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_4(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_6(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_5(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_7(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_6(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_8(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_7(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_9(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_8(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_10(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_9(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_11(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_10(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_12(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_11(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_13(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_12(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_14(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_13(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_15(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_14(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_16(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_15(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_17(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_16(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_18(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_17(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_19(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_18(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_20(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_19(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_21(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_20(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_22(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_21(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_23(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_22(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_24(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_23(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_25(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_24(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_26(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_25(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_27(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_26(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_28(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_27(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_29(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_28(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_30(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_29(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_31(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_30(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_32(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_31(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_33(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_32(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_34(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_33(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_35(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_34(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_36(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_35(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_37(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_36(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_38(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_37(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_39(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_38(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_40(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_39(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_41(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_40(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_42(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_41(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_43(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_42(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_44(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_43(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_45(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_44(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_46(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_45(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_47(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_46(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_48(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_47(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_49(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_48(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_50(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_49(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_51(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_50(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_52(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_51(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_53(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_52(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_54(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_53(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_55(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_54(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_56(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_55(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_57(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_56(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_58(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_57(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_59(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_58(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_60(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_59(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_61(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_60(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_62(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_61(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_63(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_62(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_64(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_63(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_65(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_64(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_66(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_65(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_67(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_66(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_68(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_67(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_69(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_68(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_70(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_69(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_71(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_70(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_72(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_71(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_73(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_72(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_74(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_73(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_75(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_74(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_76(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_75(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_77(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_76(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_78(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_77(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_79(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_78(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_80(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_79(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_81(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_80(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_82(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_81(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_83(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_82(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_84(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_83(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_85(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_84(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_86(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_85(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_87(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_86(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_88(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_87(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_89(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_88(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_90(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_89(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_91(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_90(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_92(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_91(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_93(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_92(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_94(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_93(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_95(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_94(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_96(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_95(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_97(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_96(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_98(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_97(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_99(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_98(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_100(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_99(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_101(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_100(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_102(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_101(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_103(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_102(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_104(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_103(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_105(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_104(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_106(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_105(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_107(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_106(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_108(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_107(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_109(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_108(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_110(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_109(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_111(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_110(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_112(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_111(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_113(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_112(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_114(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_113(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_115(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_114(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_116(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_115(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_117(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_116(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_118(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_117(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_119(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_118(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_120(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_119(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_121(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_120(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_122(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_121(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_123(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_122(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_124(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_123(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_125(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_124(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_126(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_125(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_127(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_126(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_128(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_127(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_129(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_128(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_130(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_129(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_131(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_130(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_132(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_131(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_133(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_132(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_134(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_133(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_135(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_134(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_136(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_135(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_137(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_136(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_138(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_137(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_139(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_138(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_140(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_139(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_141(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_140(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_142(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_141(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_143(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_142(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_144(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_143(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_145(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_144(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_146(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_145(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_147(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_146(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_148(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_147(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_149(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_148(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_150(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_149(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_151(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_150(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_152(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_151(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_153(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_152(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_154(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_153(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_155(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_154(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_156(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_155(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_157(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_156(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_158(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_157(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_159(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_158(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_160(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_159(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_161(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_160(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_162(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_161(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_163(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_162(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_164(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_163(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_165(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_164(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_166(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_165(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_167(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_166(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_168(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_167(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_169(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_168(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_170(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_169(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_171(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_170(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_172(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_171(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_173(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_172(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_174(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_173(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_175(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_174(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_176(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_175(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_177(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_176(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_178(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_177(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_179(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_178(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_180(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_179(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_181(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_180(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_182(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_181(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_183(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_182(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_184(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_183(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_185(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_184(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_186(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_185(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_187(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_186(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_188(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_187(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_189(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_188(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_190(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_189(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_191(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_190(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_192(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_191(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_193(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_192(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_194(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_193(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_195(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_194(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_196(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_195(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_197(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_196(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_198(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_197(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_199(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_198(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_200(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_199(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_201(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_200(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_202(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_201(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_203(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_202(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_204(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_203(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_205(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_204(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_206(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_205(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_207(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_206(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_208(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_207(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_209(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_208(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_210(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_209(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_211(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_210(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_212(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_211(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_213(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_212(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_214(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_213(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_215(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_214(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_216(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_215(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_217(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_216(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_218(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_217(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_219(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_218(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_220(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_219(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_221(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_220(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_222(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_221(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_223(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_222(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_224(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_223(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_225(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_224(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_226(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_225(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_227(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_226(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_228(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_227(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_229(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_228(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_230(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_229(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_231(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_230(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_232(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_231(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_233(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_232(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_234(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_233(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_235(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_234(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_236(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_235(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_237(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_236(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_238(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_237(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_239(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_238(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_240(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_239(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_241(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_240(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_242(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_241(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_243(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_242(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_244(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_243(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_245(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_244(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_246(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_245(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_247(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_246(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_248(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_247(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_249(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_248(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_250(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_249(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_251(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_250(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_252(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_251(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_253(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_252(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_254(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_253(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_255(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_254(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_256(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_255(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_N(f, context, sep, count, ...) MACRO_FOREACH_##count(f, context, sep, __VA_ARGS__)
#define MACRO_ARGUMENTS(...) MACRO_ARGS_SIZE(__VA_ARGS__), __VA_ARGS__
#define MACRO_FOREACH(f, context, sep, ...) MACRO_FOREACH_N(f, context, sep, __VA_ARGS__)
#define ADD_KOMA_SEP ,
#define ADD_SEMICOLON_SEP ;
#define ADD_NO_SEP  

#endif  // TAHD_MACRO_FUNCTIONS_H
