#pragma once
#ifndef TAHD_MACRO_FUNCTIONS_H
#define TAHD_MACRO_FUNCTIONS_H

#define MACRO_ARGS_COUNT(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, res, ...) res
#define MACRO_ARGS_SIZE(...) MACRO_ARGS_COUNT(__VA_ARGS__, 16, 15, 14, 13, 12, 11, 10, 9 , 8, 7, 6, 5, 4, 3, 2, 1)

#define MACRO_FOREACH_1(f, context, sep, arg) f(context, arg)
#define MACRO_FOREACH_2(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_1(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_3(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_2(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_4(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_3(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_5(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_4(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_6(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_5(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_7(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_6(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_8(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_7(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_9(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_8(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_10(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_9(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_11(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_10(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_12(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_11(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_13(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_12(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_14(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_13(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_15(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_14(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_16(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_15(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_17(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_16(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_18(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_17(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_19(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_18(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_20(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_19(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_21(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_20(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_22(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_21(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_23(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_22(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_24(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_23(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_25(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_24(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_26(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_25(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_27(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_26(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_28(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_27(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_29(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_28(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_30(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_29(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_31(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_30(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_32(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_31(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_33(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_32(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_34(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_33(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_35(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_34(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_36(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_35(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_37(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_36(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_38(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_37(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_39(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_38(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_40(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_39(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_41(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_40(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_42(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_41(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_43(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_42(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_44(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_43(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_45(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_44(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_46(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_45(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_47(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_46(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_48(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_47(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_49(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_48(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_50(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_49(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_51(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_50(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_52(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_51(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_53(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_52(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_54(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_53(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_55(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_54(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_56(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_55(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_57(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_56(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_58(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_57(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_59(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_58(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_60(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_59(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_61(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_60(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_62(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_61(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_63(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_62(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_64(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_63(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_65(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_64(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_66(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_65(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_67(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_66(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_68(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_67(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_69(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_68(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_70(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_69(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_71(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_70(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_72(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_71(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_73(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_72(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_74(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_73(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_75(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_74(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_76(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_75(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_77(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_76(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_78(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_77(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_79(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_78(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_80(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_79(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_81(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_80(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_82(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_81(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_83(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_82(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_84(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_83(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_85(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_84(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_86(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_85(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_87(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_86(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_88(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_87(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_89(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_88(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_90(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_89(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_91(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_90(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_92(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_91(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_93(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_92(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_94(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_93(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_95(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_94(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_96(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_95(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_97(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_96(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_98(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_97(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_99(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_98(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_100(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_99(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_101(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_100(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_102(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_101(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_103(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_102(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_104(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_103(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_105(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_104(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_106(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_105(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_107(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_106(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_108(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_107(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_109(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_108(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_110(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_109(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_111(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_110(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_112(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_111(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_113(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_112(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_114(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_113(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_115(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_114(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_116(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_115(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_117(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_116(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_118(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_117(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_119(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_118(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_120(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_119(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_121(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_120(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_122(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_121(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_123(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_122(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_124(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_123(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_125(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_124(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_126(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_125(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_127(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_126(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_128(f, context, sep, arg, ...) f(context, arg) ADD_##sep MACRO_FOREACH_127(f, context, sep,__VA_ARGS__)
#define MACRO_FOREACH_N(f, context, sep, count, ...) MACRO_FOREACH_##count(f, context, sep, __VA_ARGS__)
#define MACRO_ARGUMENTS(...) MACRO_ARGS_SIZE(__VA_ARGS__), __VA_ARGS__
#define MACRO_FOREACH(f, context, sep, ...) MACRO_FOREACH_N(f, context, sep, __VA_ARGS__)
#define ADD_KOMA_SEP ,
#define ADD_SEMICOLON_SEP ;
#define ADD_NO_SEP  

#endif  // TAHD_MACRO_FUNCTIONS_H
